spring:
  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/springapp
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update